import { NextResponse } from 'next/server';
import JSZip from 'jszip';
import * as esbuild from 'esbuild';
import { generateProvider } from '../../../lib/generator';

function buildCommonJs(source: string, outfile: string): string {
  const result = esbuild.transformSync(source, {
    loader: 'ts',
    format: 'cjs',
    platform: 'node',
    target: 'es2015',
    sourcemap: false,
    minify: false,
    keepNames: true,
  });

  let code = result.code.replace(/require\(['"]node:.*?['"]\)/g, '{}');

  // Keep compatibility with Vega's provider sandbox by exposing named
  // exports directly on CommonJS `exports` as the official provider builder does.
  const exportMatch = code.match(/__export\((\w+),\s*\{([^}]+)\}\);/);
  if (exportMatch) {
    const exportsContent = exportMatch[2];
    const exportEntries = exportsContent
      .split(',')
      .map(entry => {
        const match = entry.trim().match(/(\w+):\s*\(\)\s*=>\s*(\w+)/);
        return match ? { exportName: match[1], localName: match[2] } : null;
      })
      .filter(Boolean) as { exportName: string; localName: string }[];

    const directExports = exportEntries
      .map(({exportName, localName}) => `exports.${exportName} = ${localName};`)
      .join('\n');

    code = code.replace(
      /module\.exports\s*=\s*__toCommonJS\((\w+)\);/g,
      '',
    );
    code += `\n${directExports}\n`;
  }

  return code;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const analysis = body?.analysis;
    const name = String(body?.name || analysis?.title || 'Website Provider')
      .trim()
      .slice(0, 80);

    if (!analysis?.url) {
      return NextResponse.json({error: 'Analysis is required'}, {status: 400});
    }
    if (!/^https?:\/\//i.test(analysis.url)) {
      return NextResponse.json({error: 'Analysis URL is invalid.'}, {status: 400});
    }
    if (!name) {
      return NextResponse.json({error: 'Provider name is required.'}, {status: 400});
    }

    const result = generateProvider(analysis, name);
    const zip = new JSZip();
    const providerId = result.id;

    // Build the source modules immediately so the ZIP is ready to publish as a
    // standalone provider repository. Vega does not execute the TypeScript files;
    // it fetches manifest.json and the built dist/<provider>/*.js files.
    const distFiles: Record<string, string> = {};
    for (const [path, content] of Object.entries(result.files)) {
      zip.file(path, content);
      if (path.startsWith(`providers/${providerId}/`) && path.endsWith('.ts')) {
        const moduleName = path.split('/').pop()!.replace(/\.ts$/, '');
        distFiles[`dist/${providerId}/${moduleName}.js`] = buildCommonJs(
          content,
          moduleName,
        );
      }
    }

    // A standalone manifest makes the generated repository directly usable as
    // a custom Vega provider source: https://repo -> raw repo -> manifest.json.
    const manifestEntry = result.files['manifest-entry.json'];
    const entry = manifestEntry ? JSON.parse(manifestEntry) : {
      display_name: name,
      value: providerId,
      version: '1.0',
      icon: analysis.images?.[0] || '',
      type: 'global',
      hasSettings: false,
      disabled: false,
    };
    zip.file('manifest.json', JSON.stringify([entry], null, 2));

    for (const [path, content] of Object.entries(distFiles)) {
      zip.file(path, content);
    }

    zip.file(
      'GENERATOR-NOTES.md',
      `Generated by Vega Provider Generator 2.1.\n\nSource: ${analysis.url}\nCrawled pages: ${analysis.crawledPages || 1}\n\nThis ZIP is Vega-ready for a standalone GitHub repository. It contains:\n- manifest.json\n- providers/${providerId}/ TypeScript source\n- dist/${providerId}/ pre-built JavaScript modules\n\nPublish the ZIP contents at the root of a GitHub repository. In Vega, add that GitHub repository URL (or its owner/repository source) under Settings > Provider Manager > Available Providers. Vega will fetch manifest.json and dist/${providerId}/*.js from the repository.\n\nFor adding the provider to an existing multi-provider repository, do not replace its manifest.json. Copy providers/${providerId}/ and dist/${providerId}/, then merge the generated manifest entry into the existing manifest.\n`,
    );

    const blob = await zip.generateAsync({type: 'base64'});
    return NextResponse.json({
      filename: `${result.id}-vega-provider.zip`,
      base64: blob,
      files: [...Object.keys(result.files), 'manifest.json', ...Object.keys(distFiles)],
      version: '2.1',
      providerId,
      readyToPublish: true,
    });
  } catch (e) {
    return NextResponse.json(
      {error: String(e instanceof Error ? e.message : e)},
      {status: 500},
    );
  }
}
