import {NextResponse} from 'next/server';
import JSZip from 'jszip';
import {transform} from 'sucrase';
import {generateProvider} from '../../../lib/generator';

function buildCommonJs(source: string): string {
  try {
    return transform(source, {
      transforms: ['typescript', 'imports'],
      enableLegacyTypeScriptModuleInterop: false,
      disableESTransforms: true,
    }).code.replace(/require\(['"]node:.*?['"]\)/g, '{}');
  } catch (error) {
    throw new Error(
      `Generated provider compilation failed: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const analysis = body?.analysis;
    const name = String(body?.name || analysis?.title || 'Website Provider')
      .trim()
      .slice(0, 80);

    if (!analysis?.url) {
      return NextResponse.json({error: 'Analysis is required'}, {status: 400});
    }
    if (!/^https?:\/\//i.test(analysis.url)) {
      return NextResponse.json({error: 'Analysis URL is invalid.'}, {status: 400});
    }
    if (!name) {
      return NextResponse.json({error: 'Provider name is required.'}, {status: 400});
    }

    const result = generateProvider(analysis, name);
    const zip = new JSZip();
    const providerId = result.id;
    const distFiles: Record<string, string> = {};

    for (const [path, content] of Object.entries(result.files)) {
      zip.file(path, content);
      if (path.startsWith(`providers/${providerId}/`) && path.endsWith('.ts')) {
        const moduleName = path.split('/').pop()!.replace(/\.ts$/, '');
        distFiles[`dist/${providerId}/${moduleName}.js`] = buildCommonJs(content);
      }
    }

    // Vega's provider manager turns a GitHub repository into a raw source root
    // and requests /manifest.json plus /dist/<provider>/*.js from that root.
    const manifestEntry = result.files['manifest-entry.json'];
    const entry = manifestEntry
      ? JSON.parse(manifestEntry)
      : {
          display_name: name,
          value: providerId,
          version: '1.0',
          icon: analysis.images?.[0] || '',
          type: 'global',
          hasSettings: false,
          disabled: false,
        };
    entry.hasSettings = Boolean(distFiles[`dist/${providerId}/settings.js`]);
    zip.file('manifest.json', JSON.stringify([entry], null, 2));

    for (const [path, content] of Object.entries(distFiles)) {
      zip.file(path, content);
    }

    zip.file(
      'GENERATOR-NOTES.md',
      `Generated by Vega Provider Generator 2.2.\n\nSource: ${analysis.url}\nCrawled pages: ${analysis.crawledPages || 1}\n\nThis ZIP is Vega-ready for a standalone GitHub repository. It contains:\n- manifest.json\n- providers/${providerId}/ TypeScript source\n- dist/${providerId}/ pre-built JavaScript modules\n\nPublish the ZIP contents at the root of a GitHub repository. In Vega, go to Settings > Provider Manager > + and enter that GitHub repository URL. Vega will read manifest.json and then download the built files from dist/${providerId}/.\n\nFor adding the provider to an existing multi-provider repository, do not replace its manifest.json. Copy providers/${providerId}/ and dist/${providerId}/, then merge the generated manifest entry into the existing manifest.\n`,
    );

    const blob = await zip.generateAsync({type: 'base64'});
    return NextResponse.json({
      filename: `${result.id}-vega-provider.zip`,
      base64: blob,
      files: [...Object.keys(result.files), 'manifest.json', ...Object.keys(distFiles)],
      version: '2.2',
      providerId,
      readyToPublish: true,
    });
  } catch (e) {
    return NextResponse.json(
      {error: String(e instanceof Error ? e.message : e)},
      {status: 500},
    );
  }
}
